Traceback (most recent call last):
  File "main.py", line 83, in <module>
    model.fit(train_x, train_y)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/sklearn.py", line 826, in fit
    missing=self.missing, nthread=self.n_jobs)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/core.py", line 438, in __init__
    feature_types=feature_types)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/data.py", line 504, in dispatch_data_backend
    feature_names, feature_types)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/data.py", line 221, in _from_pandas_df
    feature_types)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/data.py", line 135, in _from_numpy_array
    flatten = _transform_np_array(data)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/data.py", line 115, in _transform_np_array
    flatten = np.array(data.reshape(data.size), copy=False,
MemoryError: Unable to allocate 6.10 GiB for an array with shape (3200000, 256) and data type float64
srun: error: node007: task 0: Exited with exit code 1
